# ----------------------------
# Makefile Options
# ----------------------------

# Name of the output .bin file
NAME = ccha20t
DESCRIPTION = "ChaCha20 encryption benchmark tests"
COMPRESSED = NO

CFLAGS = -Wall -Wextra -Oz
CXXFLAGS = -Wall -Wextra -Oz

# ----------------------------

include $(shell cedev-config --makefile)
