# ----------------------------
# Makefile Options
# ----------------------------

# Name of the output .bin file
NAME = exename
DESCRIPTION = "Description of the project"
COMPRESSED = NO

CFLAGS = -Wall -Wextra -Oz
CXXFLAGS = -Wall -Wextra -Oz

# ----------------------------

include $(shell cedev-config --makefile)
