# ----------------------------
# Makefile Options
# ----------------------------

# Name of the output .bin file
NAME = rc4tst
DESCRIPTION = "RC4 encryption benchmark tests"
COMPRESSED = NO

CFLAGS = -Wall -Wextra -Oz
CXXFLAGS = -Wall -Wextra -Oz

# ----------------------------

include $(shell cedev-config --makefile)
