# ----------------------------
# Makefile Options
# ----------------------------

# Name of the output .bin file
NAME = sha1tst
DESCRIPTION = "SHA-1 hash benchmark tests"
COMPRESSED = NO

CFLAGS = -Wall -Wextra -Oz
CXXFLAGS = -Wall -Wextra -Oz

# ----------------------------

include $(shell cedev-config --makefile)
