# ----------------------------
# Makefile Options
# ----------------------------

# Name of the output .bin file
NAME = aes128t
DESCRIPTION = "AES-128 hash benchmark tests"
COMPRESSED = NO

CFLAGS = -Wall -Wextra -Oz
CXXFLAGS = -Wall -Wextra -Oz

# ----------------------------

include $(shell cedev-config --makefile)
