# ----------------------------
# Makefile Options
# ----------------------------

# Name of the output .bin file
NAME = TEST01
DESCRIPTION = "Test 01"
COMPRESSED = NO

CFLAGS = -Wall -Wextra -Oz
CXXFLAGS = -Wall -Wextra -Oz

# ----------------------------

include $(shell cedev-config --makefile)
