# ----------------------------
# Makefile Options
# ----------------------------

# Name of the output .bin file
NAME = portrw
DESCRIPTION = "Command-line tool for reading and writing IN/OUT CPU's HW ports"
COMPRESSED = NO

CFLAGS = -Wall -Wextra -Oz
CXXFLAGS = -Wall -Wextra -Oz

# ----------------------------

include $(shell cedev-config --makefile)
