# ----------------------------
# Makefile Options
# ----------------------------

# Name of the output .bin file
NAME = test02
DESCRIPTION = ""
COMPRESSED = NO

CFLAGS = -Wall -Wextra -Oz
CXXFLAGS = -Wall -Wextra -Oz

# ----------------------------

include $(shell cedev-config --makefile)
