# ----------------------------
# Makefile Options
# ----------------------------

# Name of the output .bin file
NAME = filetst3
DESCRIPTION = "Writing a new file in SD card - test 1"
COMPRESSED = NO

CFLAGS = -Wall -Wextra -Oz
CXXFLAGS = -Wall -Wextra -Oz

# ----------------------------

include $(shell cedev-config --makefile)
